# NOTE: Generated By HttpRunner v3.1.4
# FROM: testcases\demo_pactverify.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseDemoPactverify(HttpRunner):

    config = (
        Config("httprunner pactverify demo")
        .base_url("http://localhost:9999")
        .verify(False)
    )

    teststeps = [
        Step(
            RunRequest("get_auth")
            .with_variables(**{"name": "lilei", "age": 12})
            .get("/api/v1/auth")
            .with_params(**{"name": "$name", "age": "$age"})
            .teardown_hook("${pactverify($response,api_v1_auth_get_pact)}")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("verify_result", True)
            .assert_length_greater_or_equals("verify_info", 0)
        ),
    ]


if __name__ == "__main__":
    TestCaseDemoPactverify().test_start()
